conn sys as sysdba;

CREATE TABLESPACE MYSPACE1
DATAFILE '\ORACLEXE\APP\ORACLE\ORADATA\XE\myspace1.dbf' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE USER KARAYEL
IDENTIFIED BY test123
DEFAULT TABLESPACE MYSPACE1;

CREATE TABLE T1 (
   ID NUMBER,
   NAME VARCHAR2(20)
) TABLESPACE MYSPACE1;

CREATE TABLE T2 (
   ID NUMBER,
   NAME VARCHAR2(20)
) TABLESPACE MYSPACE1;

CREATE TABLE T3 (
   ID NUMBER,
   NAME VARCHAR2(20)
) TABLESPACE MYSPACE1;

CREATE TABLE T4 (
   ID NUMBER,
   NAME VARCHAR2(20)
) TABLESPACE MYSPACE1;

CREATE TABLESPACE MYSPACE12
DATAFILE '\ORACLEXE\APP\ORACLE\ORADATA\XE\myspace12.dbf' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

ALTER TABLE T4 MOVE TABLESPACE MYSPACE12;

CREATE TABLE EMPLOYEE(
   ID INT PRIMARY KEY,
   NAME VARCHAR2(20),
   PHONENUMBER VARCHAR2(11) UNIQUE,
   CONSTRAINT CHK_PHONE CHECK(PHONENUMBER LIKE '0%' AND LENGTH(PHONENUMBER) = 11)
);

INSERT INTO EMPLOYEE VALUES(
   401,
   'Mina Mina',
   '01234567891'
);

INSERT INTO EMPLOYEE VALUES(
   402,
   'Mimi',
   '01234567990'
);

INSERT INTO EMPLOYEE VALUES(
   403,
   'Karayel',
   '01234337990'
);

INSERT INTO EMPLOYEE VALUES(
   404,
   'Margery',
   '01222567891'
);

INSERT INTO EMPLOYEE VALUES(
   405,
   'Doraemon',
   '01235567990'
);

INSERT INTO EMPLOYEE VALUES(
   406,
   'Hattori',
   '01234667891'
);

INSERT INTO EMPLOYEE VALUES(
   407,
   'Nikki',
   '01234568990'
);

INSERT INTO EMPLOYEE VALUES(
   408,
   'Shinjo',
   '01243567891'
);

INSERT INTO EMPLOYEE VALUES(
   409,
   'Doraemi',
   '09034567891'
);

INSERT INTO EMPLOYEE VALUES(
   410,
   'Pippo',
   '01000567891'
);

INSERT INTO EMPLOYEE VALUES(
   411,
   'Riruru',
   '01200567891'
);

INSERT INTO EMPLOYEE VALUES(
   412,
   'Pupy',
   '01230067891'
);

SELECT
   *
FROM
   EMPLOYEE
WHERE
   PHONENUMBER LIKE '%990';

CREATE TABLE LEFT_(
   ID INT PRIMARY KEY,
   NAME VARCHAR2(20),
   SALARY VARCHAR2(10)
);

CREATE TABLE RIGHT_(
   ID INT PRIMARY KEY,
   NAME VARCHAR2(20),
   POSITION VARCHAR2(10)
);

INSERT INTO LEFT_ VALUES(
   401,
   'Mina Mina',
   '100'
);

INSERT INTO LEFT_ VALUES(
   402,
   'Mimi',
   '200'
);

INSERT INTO LEFT_ VALUES(
   403,
   'Karayel',
   '500'
);

INSERT INTO LEFT_ VALUES(
   404,
   'Margery',
   '300'
);

INSERT INTO LEFT_ VALUES(
   405,
   'Doraemon',
   '1000'
);

INSERT INTO RIGHT_ VALUES(
   404,
   'Margery',
   'low'
);

INSERT INTO RIGHT_ VALUES(
   405,
   'Doraemon',
   'high'
);

INSERT INTO RIGHT_ VALUES(
   406,
   'Shishimanu',
   'very high'
);

INSERT INTO RIGHT_ VALUES(
   407,
   'Perman',
   'medium'
);

INSERT INTO RIGHT_ VALUES(
   408,
   'Hero',
   'average'
);

SELECT
   *
FROM
   LEFT_
   LEFT JOIN RIGHT_
   ON LEFT_.ID = RIGHT_.ID;

SELECT
   *
FROM
   LEFT_
   RIGHT JOIN RIGHT_
   ON LEFT_.ID = RIGHT_.ID;

SELECT
   *
FROM
   LEFT_
   NATURAL JOIN RIGHT_;